apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kibana-system-auth
  name: kibana-system-auth
  namespace: tectonic-system
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: http
  selector:
    k8s-app: kibana-system-auth
  sessionAffinity: None
  type: ClusterIP
