apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-workload
  namespace: tectonic-system
  labels:
    k8s-app: kibana-workload
    tier: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-workload
  template:
    metadata:
      labels:
        k8s-app: kibana-workload
        tier: logging
    spec:
      containers:
      - name: kibana
        image: cfontes/kibana-xpack-less:5.5.0
        env:
        - name: CLUSTER_NAME
          value: es-workload
        - name: ELASTICSEARCH_URL
          value: http://es-workload:9200
        - name: SERVER_BASEPATH
          value: /kibana-workload
        - name: XPACK_SECURITY_ENABLED
          value: 'false'
        - name: XPACK_GRAPH_ENABLED
          value: 'false'
        - name: XPACK_ML_ENABLED
          value: 'false'
        - name: XPACK_REPORTING_ENABLED
          value: 'false'
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP
