apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-storage-admin
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: local-storage-provisioner-pv-binding
  namespace: diskadmin
subjects:
- kind: ServiceAccount
  name: local-storage-admin
  namespace: diskadmin
roleRef:
  kind: ClusterRole
  name: system:persistent-volume-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: local-storage-provisioner-node-binding
  namespace: diskadmin
subjects:
- kind: ServiceAccount
  name: local-storage-admin
  namespace: diskadmin
roleRef:
  kind: ClusterRole
  name: system:node
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: local-storage-provisioner-node-observer-binding
  namespace: diskadmin
subjects:
- kind: ServiceAccount
  name: local-storage-admin
  namespace: diskadmin
roleRef:
  kind: ClusterRole
  name: system:node-observer
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: system:node-observer
  namespace: diskadmin
rules:
- apiGroups:
  - v1
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
