apiVersion: v1
kind: Service
metadata:
  name: es-system
  namespace: tectonic-system
  labels:
    k8s-app: es-system
    tier: logging
spec:
  ports:
  - name: db
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
  selector:
    k8s-app: es-system
