apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: calico-bgp
  namespace: tectonic-system
  labels:
    k8s-app: calico-bgp
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: calico-bgp
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
  - port: http-metrics
    interval: 30s
    honorLabels: true
